### ISSUE TITLE
Any plans to add Caching policy like in Polly?

### ISSUE THREAD

**Issue by johnib** [connor4312/cockatiel#63]
Hi,

Would be happy to get to a feature parity with .NET's Polly library.
So far I'm using this library extensively.. and Caching policy is one part that is missing.

Thank you!

**Comment by moberegger** [comment]
Perhaps the policy could be built on top of (or align to) [`keyv`](https://www.npmjs.com/package/keyv). Could help get it working "out of the box" with other tools. By default, it would cache in memory, but there are adaptors for things like Redis available.

**Comment by connor4312** [comment]
Yea, I think this is probably out of scope at first glance, but would need to look into Polly more. Notably .NET has an official [IDistributedCache](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.distributed.idistributedcache?view=dotnet-plat-ext-6.0) interface so that 'any' cache can work automatically with Polly, which JavaScript does not have.

It'd be easy for a caching library to consume Cockatiel by taking policies in its operations, or wrap a caching library to that effect.

**Comment by connor4312** [comment]
I don't have any plans here.
