### ISSUE TITLE
Support to NodeJS 14

### ISSUE THREAD

**Issue by gtkatakura** [connor4312/cockatiel#67]
Hi, guys. I saw that today the nodejs support engine is target to >=16, but the nodejs 14 still is in maintenance support until 2023-04-30 as [you can see here](https://nodejs.org/en/about/releases/), could we review this decision? Maybe even removing the engine restriction? Today I don't see any related code which could restrict the usage of this library to old versions, and unfortunately at our company, we have a lot of projects which runs on old versions of NodeJS ;/

Like if you remove the engine restriction, this don't means that you have official support to lower versions than nodejs 14/16, but you enable people to use it in some way, the worst case would be building the library code using their toolchain

**Comment by connor4312** [comment]
Node 16 is needed since we [now use](https://github.com/connor4312/cockatiel/blob/master/changelog.md#300-beta0) AbortSignals over CancellationTokens. AbortSignals are the standard way to deal with cancellation in JS nowadays, and I don't plan to revert this decision.

For Node 14, you can use a [polyfill](https://www.npmjs.com/package/abortcontroller-polyfill) or stick on Cockatiel 2.x until you get a chance to upgrade.

**Comment by gtkatakura** [comment]
Not sure if I understand how I could use cockatiel 3.x + abortcontroller-polyfill with the engine restriction.

**Comment by connor4312** [comment]
ah, so your package manager enforces that restriction. Looks like `--ignore-engines` is a thing, but that's not ideal. I wish npm had something like "this package requires this peer dependency on this version of Node.js." 

In the meantime I've published a tag of cockatiel called `anyengine`, which you can install like `npm i --save cockatiel@anyengine`. This is identical to 3.0.0 but without `engines` in its package.json.

**Comment by gtkatakura** [comment]
Yes, it enforces and today I can't control the deploy workflow ;/
Thank you, I gonna use it
