### ISSUE TITLE
Question: How can I share info between servers?

### ISSUE THREAD

**Issue by Nikoms** [connor4312/cockatiel#89]
Hello,

I'd like to use cockatiel but my app is running on multiple servers. Is there a way to share a state (for circuit breaker example) between different servers? If an API is down, I would like all of them to stop sending traffic. I think everything is in-memory here, but I'd like to know if there is a way to "plug" another implementation like redis.

If it's not implemented, is it because it's a bad idea? 😅

Thank you :)

**Comment by ValeryShvyndzikau** [comment]
Hello,
I have almost the same question, I'm considering Cockatiel for the AWS serverless architecture and I need to share Circuit Breaker state between Lambda invocations. It can be DynamoDB as a storage. For example, there is a such capability Opossum library provides and can be achieved in this way:
const breakerState = breaker.toJSON();
const breaker = new CircuitBreaker({state: state});

**Comment by connor4312** [comment]
I think the needs for hydrating state, as you say in serverless, are different from sharing state.

Hydrating state is easy and I think I'll implement that for this issue.

Sharing state is very hard. You need a data store that can read and write pretty fast since we'd need to do a read pretty often. You also need to be able to do distributed locking to prevent multiple servers doing half-open tries at once. And this is an external data store, so you need failure handling for _that_ datastore too and end up with a chicken and egg problem.

This would mostly be useful for the case of large numbers of servers sending a small number of requests, which generally falls in the realm of serverless for which I think hydration is a better solution.

**Comment by ghost91-** [comment]
@connor4312 1d000749c3ccf6ed0ce3c8575b06b890264b2b60 implements (de)serializing the state of the `CircuitBreakerPolicy` class, but wouldn't we also need to do that for the state of the `IBreaker` implementations?

**Comment by connor4312** [comment]
Good catch, fixed in 3.2.1
